AWSTemplateFormatVersion: 2010-09-09
Description: DataLake - Glue Stack

Parameters:
  ProjectName:
    Type: String

  Env:
    Type: String

Resources:
  DataLakeGlueRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:ListBucket"
                  - "s3:DeleteObject"
                Resource:
                  - !Sub "arn:aws:s3:::${ProjectName}-${Env}*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Path: "/"

  DataLakeDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput: 
        Description: !Sub "Glue Database for DataLake (Env: ${Env})"
        Name: !Sub "${ProjectName}_${Env}_database"

Outputs:
  DataLakeDatabaseName:
    Value: !Ref DataLakeDatabase

  DataLakeGlueRoleArn:
    Value: !GetAtt DataLakeGlueRole.Arn